name: Cypress e2e integration tests workflow with security
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

env:
  OPENSEARCH_BRANCH: 'main'
  SECURITY_BRANCH: 'main'
  OPENSEARCH_DASHBOARDS_VERSION: 'main'
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'myStrongPassword123!'
  OPENSEARCH_VERSION: '3.4.0-SNAPSHOT'
  SECURITY_VERSION: '3.4.0.0-SNAPSHOT'
  GRADLE_VERSION: '7.6.1'
  CYPRESS_VIDEO: true
  CYPRESS_SCREENSHOT_ON_RUN_FAILURE: true

jobs:
  tests:
    name: Run Cypress E2E tests
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            cypress_cache_folder: ~/.cache/Cypress
    runs-on: ${{ matrix.os }}
    env:
      CI: 1
      TERM: xterm
    steps:

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Checkout OpenSearch
        uses: actions/checkout@v4
        with:
          repository: opensearch-project/OpenSearch
          path: OpenSearch
          ref: ${{ env.OPENSEARCH_BRANCH }}

      - name: Build WLM, publish Rule Framework to mavenLocal, and build localDistro
        run: |
          set -e
          cd OpenSearch
          ./gradlew --no-daemon :plugins:workload-management:assemble
          ./gradlew --no-daemon :modules:autotagging-commons:common:publishToMavenLocal
          ./gradlew --no-daemon :modules:autotagging-commons:spi:publishToMavenLocal
          ./gradlew --no-daemon :modules:autotagging-commons:publishToMavenLocal
          ./gradlew --no-daemon publishToMavenLocal
          ./gradlew --no-daemon localDistro

          # OPENSEARCH_VERSION already includes -SNAPSHOT; don't append another
          LOCAL_DISTRO="build/distribution/local/opensearch-${OPENSEARCH_VERSION}"
          WLM_ZIP="plugins/workload-management/build/distributions/workload-management-${OPENSEARCH_VERSION}.zip"

          # make available to later steps
          echo "LOCAL_DISTRO=$LOCAL_DISTRO" >> $GITHUB_ENV
          echo "WLM_ZIP=$WLM_ZIP" >> $GITHUB_ENV

          # also export so we can use them *in this step*
          export LOCAL_DISTRO WLM_ZIP

          echo "Local distro: $LOCAL_DISTRO"
          echo "WLM zip: $WLM_ZIP"

      - name: Checkout Security
        uses: actions/checkout@v4
        with:
          repository: opensearch-project/security
          path: security
          ref: ${{ env.SECURITY_BRANCH }}

      - name: Build Security plugin
        run: |
          set -e
          cd security
          ./gradlew --no-daemon assemble

          SEC_ZIP="build/distributions/opensearch-security-${SECURITY_VERSION}.zip"
          echo "SEC_ZIP=$SEC_ZIP" >> $GITHUB_ENV
          export SEC_ZIP

          echo "Security zip: $SEC_ZIP"

      - name: Install plugins into localDistro
        run: |
          set -e
          cd "OpenSearch/$LOCAL_DISTRO"
          bin/opensearch-plugin install --batch "file://$GITHUB_WORKSPACE/security/$SEC_ZIP"
          bin/opensearch-plugin install --batch "file://$GITHUB_WORKSPACE/OpenSearch/$WLM_ZIP"

          echo "Installed plugins:"
          bin/opensearch-plugin list || true

      # 1) Install Security demo TLS/config BEFORE starting the node
      - name: Install Security demo TLS/config (pre-start)
        run: |
          set -e
          cd "OpenSearch/$LOCAL_DISTRO/plugins/opensearch-security/tools"
          chmod +x install_demo_configuration.sh
          # The script reads OPENSEARCH_INITIAL_ADMIN_PASSWORD from env
          export OPENSEARCH_INITIAL_ADMIN_PASSWORD="${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
          # -y answers yes to prompts, -i writes demo TLS settings and files into config/
          ./install_demo_configuration.sh -y -i

      # 2) Start OpenSearch and wait for the HTTPS endpoint to respond (no auth yet)
      - name: Start OpenSearch (with Security) and wait
        run: |
          set -e
          cd "OpenSearch/$LOCAL_DISTRO"
          echo "discovery.type: single-node" >> config/opensearch.yml
          nohup bin/opensearch > os.log 2>&1 &

          echo "Waiting for HTTPS port..."
          for i in {1..60}; do
            if curl -sk https://localhost:9200 >/dev/null 2>&1; then
              echo "Port is up"; break
            fi
            echo "Attempt $i/60..."; sleep 3
          done
          curl -sk https://localhost:9200 >/dev/null 2>&1 || { echo "OpenSearch never came up"; tail -n 200 os.log || true; exit 1; }

          echo "Waiting for Security to initialize..."
          for i in {1..60}; do
            code=$(curl -sk -o /dev/null -w "%{http_code}" https://localhost:9200/_plugins/_security/health)
            # Health endpoint returns 200 once Security is initialized
            if [ "$code" -eq 200 ]; then
              echo "Security is initialized"; break
            fi
            echo "Attempt $i/60 (security not ready, http $code)..."; sleep 3
          done
          if [ "$code" -ne 200 ]; then
            echo "Security never initialized (last http code: $code)"
            echo "=== Tail os.log ==="; tail -n 200 os.log || true
            exit 1
          fi

          echo "Plugins:"
          curl -ksu "admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD}" https://localhost:9200/_cat/plugins?v || true

      # 3) Enable WLM (now that Security + TLS are active)
      - name: Enable WLM and verify
        run: |
          set -e
          # Enable WLM
          curl -sS -k --http1.1 --fail-with-body \
            -u "admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD}" \
            -X PUT "https://localhost:9200/_cluster/settings" \
            -H 'Content-Type: application/json' \
            -d '{"persistent":{"wlm.workload_group.mode":"enabled"}}'

          # Show WLM mode
          SETTINGS=$(curl -sS -k --http1.1 -u "admin:${OPENSEARCH_INITIAL_ADMIN_PASSWORD}" "https://localhost:9200/_cluster/settings")
          echo "Raw settings response: $SETTINGS"
          echo "$SETTINGS" | jq -r '.persistent.wlm.workload_group.mode // "undefined"'

      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@v4
        with:
          repository: opensearch-project/OpenSearch-Dashboards
          path: OpenSearch-Dashboards
          ref: ${{ env.OPENSEARCH_DASHBOARDS_VERSION }}

      - name: Configure OpenSearch Dashboards to talk HTTPS to OpenSearch
        run: |
           cat >> OpenSearch-Dashboards/config/opensearch_dashboards.yml << 'EOT'
           opensearch.hosts: [ "https://localhost:9200" ]
           opensearch.ssl.verificationMode: none
           server.host: "0.0.0.0"
           EOT

      - name: Checkout Query Insights Dashboards plugin
        uses: actions/checkout@v4
        with:
          path: OpenSearch-Dashboards/plugins/query-insights-dashboards

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        shell: bash
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION
      - run: node -v
      - run: yarn -v

      - name: Bootstrap plugin/OpenSearch-Dashboards
        run: |
          cd OpenSearch-Dashboards/plugins/query-insights-dashboards
          yarn osd bootstrap --single-version=loose

      - name: Run OpenSearch-Dashboards server
        run: |
          cd OpenSearch-Dashboards
          export NODE_OPTIONS="--max-old-space-size=6144 --dns-result-order=ipv4first"
          echo "Starting Dashboards..."
          nohup yarn start --no-base-path --no-watch --server.host="0.0.0.0" > dashboards.log 2>&1 &
          sleep 10
          echo "Initial Dashboards log output:"
          head -n 100 dashboards.log || true
        shell: bash

      - name: Wait for OpenSearch-Dashboards to be ready
        run: |
          echo "Waiting for OpenSearch-Dashboards to start..."
          max_attempts=150
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            if curl -sf http://localhost:5601/api/status > /dev/null 2>&1; then
              # optionally ensure overall state is 'available'
              state=$(curl -s http://localhost:5601/api/status | jq -r '.status.overall.state // .status.overall.level // "unknown"')
              if [ "$state" = "available" ] || [ "$state" = "green" ]; then
                echo "OpenSearch-Dashboards is ready! state=$state"
                echo "=== OpenSearch-Dashboards Status Debug Info ==="
                curl -s http://localhost:5601/api/status | jq '.' || curl -s http://localhost:5601/api/status
                break
              fi
            fi
            attempt=$((attempt + 1))
            echo "Attempt $attempt/$max_attempts: waiting 10s..."
            if [ $((attempt % 10)) -eq 0 ]; then
              echo "Debug: /api/status"
              curl -s -v http://localhost:5601/api/status || echo "Connection failed"
            fi
            sleep 10
          done
          if [ $attempt -eq $max_attempts ]; then
            echo "OpenSearch-Dashboards failed to start within timeout"
            curl -s -v http://localhost:5601/api/status || echo "Final connection attempt failed"
            exit 1
          fi

          echo "Waiting additional time for plugin initialization..."
          sleep 15
        shell: bash

      - name: Verify services are running
        run: |
          echo "Checking OpenSearch status..."
          curl -ksu admin:myStrongPassword123! https://localhost:9200/_cluster/health | jq '.' || echo "OpenSearch not responding"

          echo "Checking OpenSearch-Dashboards status..."
          echo "=== Full OpenSearch-Dashboards Status ==="
          curl -s http://localhost:5601/api/status || echo "OpenSearch-Dashboards not responding"
          echo "========================================"

          echo "Checking OpenSearch-Dashboards overall state..."
          curl -s http://localhost:5601/api/status | jq '.status.overall.state' || echo "Could not extract overall state"

          echo "Checking plugin endpoint..."
          curl -s http://localhost:5601/app/query-insights-dashboards || echo "Plugin endpoint not accessible"
        shell: bash
        continue-on-error: true

      - name: Install Cypress
        run: |
          cd OpenSearch-Dashboards/plugins/query-insights-dashboards
          npx cypress install
        shell: bash

      - name: Get Cypress version
        id: cypress_version
        run: |
          cd OpenSearch-Dashboards/plugins/query-insights-dashboards
          echo "::set-output name=cypress_version::$(cat ./package.json | jq '.dependencies.cypress' | tr -d '"')"

      - name: Cache Cypress
        id: cache-cypress
        uses: actions/cache@v4
        with:
          path: ${{ matrix.cypress_cache_folder }}
          key: cypress-cache-v2-${{ matrix.os }}-${{ hashFiles('OpenSearch-Dashboards/plugins/query-insights-dashboards/package.json') }}

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: OpenSearch-Dashboards/plugins/query-insights-dashboards
          command: >
            yarn run cypress run
            --spec "cypress/e2e/wlm/**/*.cy.{js,jsx,ts,tsx}"
            --config defaultCommandTimeout=120000,requestTimeout=120000,responseTimeout=120000,pageLoadTimeout=180000,taskTimeout=120000,execTimeout=120000
          wait-on: 'http://localhost:5601'
          wait-on-timeout: 1200
          browser: chrome
        env:
          CYPRESS_CACHE_FOLDER: ${{ matrix.cypress_cache_folder }}
          CI: true
        timeout-minutes: 120

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.os }}
          path: OpenSearch-Dashboards/plugins/query-insights-dashboards/cypress/screenshots

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos-${{ matrix.os }}
          path: OpenSearch-Dashboards/plugins/query-insights-dashboards/cypress/videos
